name: CI testing

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:
  # Trigger the workflow on push or pull request, but only for the master branch
  push:
    branches: [main, "ci/*"]
  pull_request:
    branches: [main]

jobs:
  pytest:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macOS-10.15, windows-2019]
        python-version: [3.9]

    # Timeout: https://stackoverflow.com/a/59076067/4521646
    timeout-minutes: 35

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    #- name: Clone Lightning Repo
    #  uses: actions/checkout@v3
    #  with:
    #    repository: PyTorchLightning/lightning
    #    token: ${{ secrets.PAT_GHOST }}
    #    ref: 'master'
    #    path: lightning

    #- name: Install Lightning
    #  run: |
    #    cd lightning
    #    pip install -r requirements.txt
    #    pip install -e .
    #  shell: bash

    - name: Install dependencies
      run: |
        python --version
        pip --version
        pip install --requirement requirements.txt --upgrade --quiet --find-links https://download.pytorch.org/whl/cpu/torch_stable.html
        pip install --requirement tests/requirements.txt --quiet
        pip list
      shell: bash

    - name: Tests
      env:
        SLACK_CHANNEL_ID: ${{secrets.SLACK_CHANNEL_ID}}
        SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}
      run: |
        coverage run --source lit_slack -m py.test lit_slack tests -v --junitxml=junit/test-results-${{ runner.os }}-${{ matrix.python-version }}.xml

    - name: Statistics
      if: success()
      run: |
        coverage report
